export const DRAWER_MENU_LABEL = {
  DASHBOARD: 'DASHBOARD',
  KANBAN: 'KANBAN',
  USERS: 'USERS',
  LIST: 'LIST',
  ACCESSLOGS: 'ACCESSLOGS',
  PLAY_BACKGROUND: 'PLAY_BACKGROUND',

  DEVICE: 'DEVICE',
  DEVICE_ADD: 'DEVICE_ADD',
  DEVICE_LIST: 'DEVICE_LIST',
  DEVICE_LOGS: 'DEVICE_LOGS',

  WAREHOUSE: 'WAREHOUSE',
  WAREHOUSE_ADD: 'WAREHOUSE_ADD',
  WAREHOUSE_LIST: 'WAREHOUSE_LIST',
};
