export const DRAWER_MENU_LABEL = {
  DASHBOARD: 'DASHBOARD',
  KANBAN: 'KANBAN',
  USERS: 'USERS',
  PLAY_BACKGROUND: 'PLAY_BACKGROUND',

  DEVICE: 'DEVICE',
  DEVICE_ADD: 'DEVICE_ADD',
  DEVICE_LIST: 'DEVICE_LIST',
};
