export const PATH_NAME = {
  ROOT: '/',
  ERROR_404: '/404',
  ERROR_403: '/403',
  DASHBOARD: '/dashboard',
  PLAY_BACKGROUND: '/playbackground',
  LOGIN: '/login',
  DEVICE: '/devices',
  DEVICE_LIST: '/device/list',
  DEVICE_ADD: '/device/add',
  USER_ADD: '/users/add',
  USERS: '/users',
  USERS_LIST: '/users',
  KANBAN: '/kanban',
  USERS_ACCESS_LOGS: '/users/accesslogs',
};
